package mapToValue;

public enum InputReportType {
    REPORT,
    DAILY,
    DAILY_BLOG,
    INVESTMENT,
    INVESTMENT_BLOG,
    PRODUCT_REVIEW,
    PRODUCT_REVIEW_BLOG,
    INDEPTH,
    INDEPTH_DAILY,
    INDEPTH_BLOG,
    JOURNAL_NOTE_BLOG,
    JOURNAL_NOTE,
    SOCIAL_MEDIA_FACEBOOK,
    SOCIAL_MEDIA_BLOG,
    SOCIAL_MEDIA_X,
    SOCIAL_MEDIA_YOUTUBE
}
